version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: user-service-db
    restart: always
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
