apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=           # base64(admin)
  POSTGRES_PASSWORD: cGFzc3dvcmQ=   # base64(password)
  POSTGRES_DB: dXNlci1zZXJ2aWNl     # base64(user-service)